global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "zombi"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["54.169.76.184:8080"]
        labels:
          instance: "ec2-t3micro"
